doctrine:
    dbal:
        connections:
            default:
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                driver: pdo_mysql
                server_version: "5.7"
                url: "%env(resolve:DATABASE_URL)%"
    orm:
        auto_generate_proxy_classes: true
        mappings:
            App:
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
